[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "iothook"
authors = [{name = "electrocoder", email = "electrocoder@gmail.com"}]
dynamic = ["version", "description"]
