# Generated by Django 4.2.2 on 2023-06-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0004_alter_device_user'),
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data',
                                    to='devices.device'),
        ),
    ]
