# Generated by Django 4.2.2 on 2023-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datas', '0006_data_field_4_data_field_5_data_field_6_data_field_7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='enable',
            field=models.BooleanField(default=True, help_text='Enable/Disable'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_1',
            field=models.CharField(help_text='Enter a field value', max_length=30, verbose_name='1. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_2',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='2. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_3',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='3. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_4',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='4. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_5',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='5. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_6',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='6. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_7',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='7. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_8',
            field=models.CharField(blank=True, help_text='Enter a field value', max_length=30, null=True,
                                   verbose_name='8. Field Value'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
    ]
