# Generated by Django 2.2.18 on 2021-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cihaz adını giriniz', max_length=30, verbose_name='İsim')),
                ('slug', models.SlugField(help_text='Url adres (Otomatik alınır)')),
                ('image',
                 models.ImageField(default='images/image.png', help_text='Resim seçiniz', upload_to='images/%Y/%m/%d',
                                   verbose_name='Resim')),
                ('tags', models.CharField(blank=True, help_text='Etiket(leri) yazınız', max_length=50,
                                          verbose_name='Etiket(ler)')),
                ('link_external_site', models.URLField(blank=True, help_text='Lütfen Web site adresi yazınız',
                                                       verbose_name='Web site adresi')),
                (
                    'field_1',
                    models.CharField(help_text='Enter a field name', max_length=30, verbose_name='1. Alan Adı')),
                ('field_2', models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                             verbose_name='2. Alan Adı')),
                ('field_3', models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                             verbose_name='3. Alan Adı')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('enable', models.BooleanField(default=True, help_text='Aktif/Pasif', verbose_name='Aktif')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
