# Generated by Django 4.2.2 on 2023-06-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0002_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
