# Generated by Django 4.2.2 on 2023-06-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0004_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='read_api_key',
            field=models.CharField(blank=True, help_text='API Key (Get automatically), MQTT icin secret_username',
                                   max_length=90, verbose_name='Read Api Key'),
        ),
        migrations.AddField(
            model_name='device',
            name='write_api_key',
            field=models.CharField(blank=True, help_text='API Key (Get automatically), MQTT icin secret_password',
                                   max_length=90, verbose_name='Write Api Key'),
        ),
    ]
