# Generated by Django 4.2.2 on 2023-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0005_device_read_api_key_device_write_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='field_4',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                   verbose_name='4. Alan Adı'),
        ),
        migrations.AddField(
            model_name='device',
            name='field_5',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                   verbose_name='5. Alan Adı'),
        ),
        migrations.AddField(
            model_name='device',
            name='field_6',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                   verbose_name='6. Alan Adı'),
        ),
        migrations.AddField(
            model_name='device',
            name='field_7',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                   verbose_name='7. Alan Adı'),
        ),
        migrations.AddField(
            model_name='device',
            name='field_8',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30,
                                   verbose_name='8. Alan Adı'),
        ),
    ]
