# Generated by Django 4.2.2 on 2023-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0007_alter_device_field_2_alter_device_field_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='enable',
            field=models.BooleanField(default=True, help_text='Enable/Disable'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_1',
            field=models.CharField(help_text='Enter a field name', max_length=30, verbose_name='1. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_2',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='2. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_3',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='3. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_4',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='4. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_5',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='5. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_6',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='6. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_7',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='7. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_8',
            field=models.CharField(blank=True, help_text='Enter a field name', max_length=30, null=True,
                                   verbose_name='8. Field Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(default='images/image.png', help_text='Select Image', upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='device',
            name='link_external_site',
            field=models.URLField(blank=True, help_text='Web address write please'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Device name', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='read_api_key',
            field=models.CharField(blank=True, help_text='API_KEY (Automatically generated), for MQTT secret_username',
                                   max_length=90),
        ),
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(help_text='Url address (Automatically generated)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='tags',
            field=models.CharField(blank=True, help_text='Tag(s) write please', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='write_api_key',
            field=models.CharField(blank=True, help_text='API_KEY (Automatically generated), for MQTT secret_password',
                                   max_length=90),
        ),
    ]
